sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '10'
before_script:
  - npm prune
  - npm update
script:
  - npm run lint
  - npm run test
after_success:
  - npx semantic-release

